### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by ccrook** [linz/snap#1]
The snap software suite is due a major overhaul.  The main steps of this are likely to be:
- [ ] convert to a cmake build system
- [ ] automate tests and testing
- [ ] create installation for linux, including packaging, splitting into multiple packages (coordinate system, libraries, command line programs, gui programs).  Consider other installation options for Windows.
- [ ] refactoring code to make better use of C++, STL, boost and remove extraneous string handling and utility code
- [ ] rationalize scripting language(s).  Consider integration with python or similar as scripting language rather than perl and snapscript custom language (may be less convenient for windows platform?)
- [ ] database integration for mark and observation data
- [ ] make strings unicode
- [ ] possibly split into multiple repositories (some components are already in separate repositories which could be rationalized, eg coordinate systems, concord)
